# Generated by Django 4.2.10 on 2024-03-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava_gateway', '0002_stravaathlete_backfill_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stravaathlete',
            old_name='expires_at',
            new_name='access_token_expires_at',
        ),
    ]
