# Generated by Django 4.2.10 on 2024-07-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strava_gateway', '0003_rename_expires_at_stravaathlete_access_token_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaSettings',
            fields=[
                ('setting_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('setting_value', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stravaathlete',
            name='id',
        ),
        migrations.AlterField(
            model_name='stravaathlete',
            name='athlete_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StravaActivity',
            fields=[
                ('activity_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=255, null=True)),
                ('distance', models.FloatField(null=True)),
                ('moving_time', models.PositiveIntegerField(null=True)),
                ('elapsed_time', models.PositiveIntegerField(null=True)),
                ('total_elevation_gain', models.FloatField(null=True)),
                ('sport_type', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('trainer', models.BooleanField(null=True)),
                ('average_speed', models.FloatField(null=True)),
                ('max_speed', models.FloatField(null=True)),
                ('avg_heart_rate', models.PositiveIntegerField(null=True)),
                ('is_activity_interval_training', models.BooleanField(null=True)),
                ('athlete_id', models.ForeignKey(db_column='athlete_id', on_delete=django.db.models.deletion.CASCADE, to='strava_gateway.stravaathlete')),
            ],
        ),
    ]
