# Generated by Django 4.2.10 on 2024-07-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_gateway', '0005_stravaactivity_is_full_activity_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='avg_heart_rate_zone',
            field=models.IntegerField(choices=[(1, 'Z1'), (2, 'Z2'), (3, 'Z3'), (4, 'Z4'), (5, 'Z5')], null=True),
        ),
        migrations.AddField(
            model_name='stravaactivity',
            name='has_heartrate',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stravaactivity',
            name='max_heartrate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stravaathlete',
            name='hr_zones',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='avg_heart_rate',
            field=models.FloatField(null=True),
        ),
    ]
