# Generated by Django 4.2.10 on 2024-07-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava_gateway', '0006_stravaactivity_avg_heart_rate_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stravaactivity',
            name='is_activity_interval_training',
        ),
    ]
