# Generated by Django 4.2.10 on 2024-07-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_gateway', '0007_remove_stravaactivity_is_activity_interval_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stravaactivity',
            old_name='avg_heart_rate',
            new_name='average_heartrate',
        ),
        migrations.RenameField(
            model_name='stravaactivity',
            old_name='avg_heart_rate_zone',
            new_name='average_heartrate_zone',
        ),
        migrations.AddField(
            model_name='stravaactivity',
            name='is_race',
            field=models.BooleanField(null=True),
        ),
    ]
