# Generated by Django 4.2.10 on 2024-07-05 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strava_gateway', '0004_stravasettings_remove_stravaathlete_id_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='strava_athlete_id',
            field=models.ForeignKey(db_column='athlete_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='strava_gateway.stravaathlete'),
        ),
    ]
