# Generated by Django 4.2.10 on 2024-07-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_name_customuser_strava_athlete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
