# Generated by Django 4.2.10 on 2024-03-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaathlete',
            name='backfill_progress',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
